name: Deploy Now

on: [push]

jobs:
  deploy-now:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          project: db01f226-4164-447f-bc0b-7ae30e3dbccc
          service-host: api-us.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Hugo
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: peaceiris/actions-hugo@v2
        with:
          extended: true
          hugo-version: '0.74.3'
      - name: Build project
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: hugo --gc --minify -b ${{ steps.project.outputs.site-url }}
      - name: Deploy build
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          branch-id: ${{ steps.project.outputs.branch-id }}
          service-host: api-us.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: public
          project: db01f226-4164-447f-bc0b-7ae30e3dbccc
          storage-quota: ${{ steps.project.outputs.storage-quota }}
